# Generated by Django 4.0.4 on 2022-04-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='department',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=1, max_length=200, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default=1, max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
