# Generated by Django 4.0.4 on 2022-05-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_remove_location_department_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=300, verbose_name='Название службы')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=1, max_length=300, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=100, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default=1, max_length=300, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.categorycontact', verbose_name='Название службы'),
        ),
    ]
