# Generated by Django 4.0.5 on 2022-07-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0008_remove_contact_phone_categorycontact_department_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail1',
            name='pin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ПИН'),
        ),
    ]
