# Generated by Django 4.0.5 on 2022-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0010_mail1_type_of_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail2',
            name='type_of_mail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид обращения'),
        ),
    ]
