# Generated by Django 4.0.4 on 2022-04-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default=1, max_length=200, verbose_name='Источник'),
            preserve_default=False,
        ),
    ]
