# Generated by Django 4.0.4 on 2022-05-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.CharField(default=1, max_length=500, verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
    ]
