# Generated by Django 4.0.4 on 2022-05-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.CharField(blank=True, default='#', max_length=500, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
