# Generated by Django 4.0.4 on 2022-06-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
