# Generated by Django 4.0.5 on 2022-06-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='announcement_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='news',
            name='announcement_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_ky',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
    ]
