# Generated by Django 4.0.5 on 2022-07-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название мероприятия')),
                ('title_ky', models.CharField(max_length=300, null=True, verbose_name='Название мероприятия')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Название мероприятия')),
                ('score1', models.CharField(max_length=100, verbose_name='Отчет до')),
                ('score1_ky', models.CharField(max_length=100, null=True, verbose_name='Отчет до')),
                ('score1_ru', models.CharField(max_length=100, null=True, verbose_name='Отчет до')),
                ('score2', models.CharField(max_length=100, verbose_name='Отчет после')),
                ('score2_ky', models.CharField(max_length=100, null=True, verbose_name='Отчет после')),
                ('score2_ru', models.CharField(max_length=100, null=True, verbose_name='Отчет после')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Срок отчета')),
                ('title_ky', models.CharField(max_length=300, null=True, verbose_name='Срок отчета')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Срок отчета')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-id'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
    ]
