# Generated by Django 4.0.5 on 2022-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_statistic_statisticcategory_alter_gallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Статистика ID',
                'verbose_name_plural': 'Статистика ID',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['id'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterModelOptions(
            name='statisticcategory',
            options={'ordering': ['id'], 'verbose_name': 'Категория статистики', 'verbose_name_plural': 'Категория статистики'},
        ),
    ]
