# Generated by Django 4.0.4 on 2022-06-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-id'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-id'], 'verbose_name': 'Ссылки', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
