# Generated by Django 4.0.5 on 2022-06-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_faq_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['id'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['id'], 'verbose_name': 'Ссылки', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
