# Generated by Django 4.0.4 on 2022-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='text',
        ),
        migrations.AddField(
            model_name='home',
            name='tagline2',
            field=models.TextField(default=1, verbose_name='Мини слоган'),
            preserve_default=False,
        ),
    ]
