# Generated by Django 4.0.4 on 2022-04-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_home_text_home_tagline2'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название о службе')),
            ],
        ),
        migrations.CreateModel(
            name='TaskText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_task_text', to='home.about')),
            ],
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-task-image', verbose_name='Фото задачи')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y', to='home.about')),
            ],
        ),
        migrations.CreateModel(
            name='PowerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_power_text', to='home.about')),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название полномочий')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_power', to='home.about')),
            ],
        ),
        migrations.CreateModel(
            name='AboutVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-video', verbose_name='Фото на видео')),
                ('video', models.CharField(max_length=500, verbose_name='Ссылка на видео')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_videos', to='home.about')),
            ],
        ),
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Номер порядка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_texts', to='home.about')),
            ],
        ),
        migrations.CreateModel(
            name='AboutTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название основных задач службы')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_tasks', to='home.about')),
            ],
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-images', verbose_name='Фото')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='home.about')),
            ],
        ),
    ]
