# Generated by Django 4.0.5 on 2022-06-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gosorgan_alter_about_options_alter_home_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['id'], 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['id'], 'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
    ]
