# Generated by Django 4.0.5 on 2022-06-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_about_options_alter_home_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttext',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
