# Generated by Django 4.0.5 on 2022-06-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_abouttext_text_ky_abouttext_text_ru'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AddField(
            model_name='about',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название о службе'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название о службе'),
        ),
    ]
