# Generated by Django 4.0.5 on 2022-06-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_home_about_title_ky_about_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Обращение'),
        ),
    ]
