# Generated by Django 4.0.5 on 2022-06-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Обращение'),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Обращение'),
        ),
    ]
