# Generated by Django 4.0.5 on 2022-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_abouttask_title_ky_abouttask_title_ru_power_title_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gosorgan',
            name='name_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='gosorgan',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
