# Generated by Django 4.0.4 on 2022-04-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='center',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='north',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='south',
        ),
        migrations.AddField(
            model_name='structure',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Структура'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.structure', verbose_name='Структура')),
            ],
        ),
    ]
