# Generated by Django 4.0.4 on 2022-04-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_structure_center_remove_structure_north_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='icon',
            field=models.CharField(default=1, max_length=100, verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
