# Generated by Django 4.0.4 on 2022-05-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_remove_structure_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuretype',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='about.structure', verbose_name='Структура'),
        ),
    ]
