# Generated by Django 4.0.4 on 2022-05-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_structuretype_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Структура')),
            ],
        ),
        migrations.RemoveField(
            model_name='structure',
            name='title',
        ),
        migrations.AddField(
            model_name='structure',
            name='name',
            field=models.CharField(default=1, max_length=300, verbose_name='Имя и должность'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StructureType',
        ),
        migrations.AddField(
            model_name='structure',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='about.category', verbose_name='Отдел'),
            preserve_default=False,
        ),
    ]
