# Generated by Django 4.0.4 on 2022-06-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_category_remove_structure_title_structure_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Структура', 'verbose_name_plural': 'Структура'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-id'], 'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'ordering': ['-id'], 'verbose_name': 'Руководство', 'verbose_name_plural': 'Руководство'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['-id'], 'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
