# Generated by Django 4.0.5 on 2022-06-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_management_options_management_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Структура', 'verbose_name_plural': 'Структура'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['id'], 'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['id'], 'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
