# Generated by Django 4.0.5 on 2022-06-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_category_options_alter_history_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон'),
        ),
    ]
