# Generated by Django 4.0.5 on 2022-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_category_title_ky_category_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history_ru',
            field=models.TextField(null=True),
        ),
    ]
