# Generated by Django 4.0.5 on 2022-07-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_history_history_ky_history_history_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
